### ISSUE TITLE
error in AVAudioSession.mm

### ISSUE THREAD

**Issue by shangyusu** [oney/react-native-webrtc#108]
as title,
I run my program in iOS 9.3.2.

```
ERROR:    [Thread 0x0x1324a6cd0] AVAudioSession.mm:692: -[AVAudioSession setActive:withOptions:error:]: Deactivating an audio session that has running I/O. All I/O should be stopped or paused prior to deactivating the audio session.
```

Any idea would be very helpful, thanks!

**Comment by zxcpoiu** [comment]
are you using [react-native-incall-manager](https://github.com/zxcpoiu/react-native-incall-manager) or not?
if it is an issue of `react-native-incall-manager`, please track issues there.

this happens because you `deactivate` an currently playing audio session. It's more like a programming error or race conditions.
I've seen it before a lots, it does not affect my app nor my devices.
an ugly annoying warning though.
