### ISSUE TITLE
On second usage getUserMedia return grey screen

### ISSUE THREAD

**Issue by kononenko-a-m** [oney/react-native-webrtc#116]
Hello,

I try to use react-native-webrtc, and faced with interesting behaviour, when first time I get local media stream with getUserMedia - it's working fine. I can see that stream correctly shown in RTCView.

But when, I refresh app - I see only grey screen without media from my camera. If I close app, and then open it again, local media stream works fine.

Tested both on iPhone and Android.

Can you please help with it?

**Comment by zxcpoiu** [comment]
related #101 #104

To be honest, I rarely use video, so have no ideas what's going on and I may be wrong.

What I guess, at least in current implementation of react-native-webrtc, is to have best control to native stream, said, you pass ( mapped ) a `stream` to `RTCView` and:

you MAY have to release/pause native stream/peerConnection gracefully/cleanly before your component unmount.
you MAY have to use the same or a brand new native stream instance when you back to your component.

**in telcom terms, for example:**

you have a `video render page / incall page` which contains RTCView component.
each time just before you are making a call or receiving a call, you create that `incall page`, and set newly created video stream in to newly mounted RTCView.

you should see `componentDidMount()` event each time, otherwise, you are not creating a new component.

after that call ends ( hangup ), release your stream ( may be close whole peerConnection instance ), and destroy your `incall page`.
you should see `ComponentWillUnmount()` as well.

dig into life cycle is a good starting point.
p.s. reload app just reload JS only, it would not bother native modules.

my two cents.

**Comment by kononenko-a-m** [comment]
thanks @zxcpoiu !

But that' what I have in the app. Component with call actually 1 entry in navigation, when it's opened all navigation history is removed, and when it's over, navigation history removed as well in amount of 1 call component. So RTCView 100% removed. Also, I did some debugging and checked, that release function has been called. For getting stream I always use getUserMedia, so should be ok.

I don't think that I using it's incorrectly, at least from pov of how it should work. I suggest, that there might be some cache inside native components, which create corrupted instance of media stream.

If tbh I think that there something might be webrtc-build-scripts

**Comment by zxcpoiu** [comment]
Hmm...then my limited knowledge could not help here :disappointed: 

**just to be clear for geeks who want to dig into this:**

* we use `webrtc-build-scripts` to build our native library on both android and iOS
* so to dig into native code problems, you should go webrtc repository itself.

#79 collected all version stuffs

**Comment by lyubomir** [comment]
You may want to try the fork of the Jitsi community at https://github.com/jitsi/react-native-webrtc.

**Comment by zxcpoiu** [comment]
#123

**Comment by zxcpoiu** [comment]
please try #123 to see if it works.

**Comment by rohitgupta87410** [comment]
Anyone find the solution of this issue . I have also got same issue .

**Comment by mobileDevNativeCross** [comment]
Guys, any news about this bug?

**Comment by seb0zz** [comment]
This might also be linked to #209

**Comment by kapilgorve** [comment]
I faced same issue when doing another call my video view will be in frozen state from previous call. Setting the source as empty on call end solved problem for me. 
`  close() {
    container.setState({ selfViewSrc: '' });
}`

**Comment by zxcpoiu** [comment]
close via #434
