### ISSUE TITLE
Video chat volume is too low

### ISSUE THREAD

**Issue by tiensonqin** [oney/react-native-webrtc#125]
First of all, great job, without this component I won't release my app.

Anyone experience this on iphone?
Some of my users told me that they can't hear me, the volume is too low. 

My app is on the app store, 
https://itunes.apple.com/us/app/lym/id1134985541?ls=1&mt=8
So really need to fix this bug, 
RN && webrtc newbie, could anyone help me?

**Comment by zxcpoiu** [comment]
oops, I am experiencing it on Android, iOS works great though.

on android, the default threshold may differ by devices, so you may want to control it according your experiences.

on ios, they officially recommended to implement [MPVolumeView](https://developer.apple.com/reference/mediaplayer/mpvolumeview)

I'm not sure if it is related to webrtc itself, but you try checking/increasing volume to see if it back to normal

**Comment by oney** [comment]
@zxcpoiu Me, too. I only got low volume problem on Android. iOS goes well.

**Comment by tiensonqin** [comment]
@zxcpoiu @oney sorry for the late response, 
setForceSpeakerphoneOn works for me on IOS.

```clojure
(.setForceSpeakerphoneOn incall-manager true)
```

**Comment by davidperrenoud** [comment]
I think this issue should be renamed: "Use speakerphone by default instead of ear speaker".

Should we advise using `setForceSpeakerphoneOn` from the [react-native-incall-manager](https://github.com/zxcpoiu/react-native-incall-manager) module? Or should we implement this directly in react-native-webrtc?

On iOS, this can be implemented with [`AVAudioSessionModeVideoChat`](https://developer.apple.com/library/content/documentation/Audio/Conceptual/AudioSessionProgrammingGuide/AudioSessionBasics/AudioSessionBasics.html#//apple_ref/doc/uid/TP40007875-CH3-SW2) and on Android with [`setSpeakerphoneOn`](https://developer.android.com/reference/android/media/AudioManager.html#setSpeakerphoneOn(boolean)).

**Comment by zxcpoiu** [comment]
We discuss this a little bit before and guess maybe it is better to **make this library agnostic**.
Because there are tons of use cases, some may have it's own logic to audio/video routes or different implementation when to screen on/off and proximity and so on.

given that the complexity to maintain `audio/video/screen/locker/proximity`, we decide to split these logic in different repository. that's the reason why `react-native-incall-manager` was born.

I think the best place to have this utils is, for example, `RCTWebRTCDemo`, which we can implement some simple utils like you described above, or an example how to integrate with `react-native-incall-manager` for different use cases.

my two cents
