### ISSUE TITLE
black bar at the bottom when popping screen

### ISSUE THREAD

**Issue by jjdp** [oney/react-native-webrtc#212]
Anyone encoutered this. happens on android 6.0 and 5.0 and genymotion.
It sometimes happens when i pop the screen from the stack. or change the height of the modal (some parts, i use modal instead of a screen). 

i have double checked everything. Tried setting the RTCView stream url to null before unmounting or rerendering null instead instead of RTCView.

im pretty sure this is related to WebRTCView.java. @oney @zxcpoiu any thoughts?

![1](https://cloud.githubusercontent.com/assets/5244520/22682501/e7ec2b14-ed4d-11e6-8f85-fb0cf25b607b.png)

**Comment by taylangocmen** [comment]
I experience a similar problem and have a hacky solution;

Setup: (everything built from source, yarn locked the versions)
* react-native ~v.0.43.1 (built from source from a specific commit around v0.43.1)
* react-native-web-rtc v1.54.7

Problem:
* After the video chat is over between two parties, the party that got hung up on gets a black screen as the RTCView component unmounts
* Realized if the phone is rotated or the state changes with partial | full black screen, it goes away

Hack:
* I am not pushing/popping the RTCView component to the navigator
* I have it rendering as a nullable, component option in my `<App ... />` component, on top of everything else
* After the chat ends I `setTimeout`, to `forceUpdate` the `<App ... />` component

If anyone has a real solution and can share, that would be great.

**Comment by saghul** [comment]
No follow-up, closing.

**Comment by konradkierus** [comment]
I've encountered a similar issue on Galaxy S7 when RTCView was in 'cover' scaling mode.

Setup:
- I'm using react-navigation and problem was disappearing only when I was leaving the screen (I've tried only going back in navigation stack).
- I've only needed remote video stream so my remote RTCView looked like this: `<RTCView key={1} streamURL=... />`
- View/component which was inside the navigation stack was displaying various call states in single render() method with a few conditions ('ifs').

Hack:
- I've created a second RTCView with different key which looked like this: `<RTCVIew key={13} style={{ position: 'absolute', width: 0, height: 0 }}` and I've put this second RTCView inside every other 'else' component where the main RTCView wasn't used. So it looked something like below:
```js
render() {
  if (call.hasVideo) {
    return <View><RTCView key={1} streamURL=... /></View>
  } else {
    return (
      <View>
        <RTCVIew key={13} style={{ position: 'absolute', width: 0, height: 0 }} /> 
        .. .other components ...
      </View>
    );
  }
}
```

Hope this helps someone when they encounter similar problem.
I've tried to change onLayout methods and other Android stuff but without success so it looks more like a problem with my setup rather than a problem with the library itself.

**Comment by nguyenanhthai** [comment]
Same issue

**Comment by nguyenanhthai** [comment]
Using **contain** for **objectFit** can help resolve issue

**Comment by jjdp** [comment]
@nguyenanhthai how does the video work for contain? does it have padding?

**Comment by nguyenanhthai** [comment]
@jjdp yes it has padding

**Comment by jjdp** [comment]
i guess that won't help for full screen

**Comment by Chocolladin** [comment]
Hi, try something like this : 
      {**creatorStream &&** (
        <RTCView
          streamURL={creatorStream?.toURL()}
          style={{ flex: 1, backgroundColor: 'blue' }}
          objectFit="cover"
        />
      )}

Regards,  Bertrand
