### ISSUE TITLE
UWP Support?

### ISSUE THREAD

**Issue by Natrium83** [oney/react-native-webrtc#238]
As Microsoft has published a UWP port for WebRTC do you plan to include this for desktop etc. use?

**Comment by zxcpoiu** [comment]
firstly, don't know about react native for windows UWP and could not speak c# though, but it sounds interesting. happy to see it of course.

I don't think we can have it done any time soon, unless someone has experiences and able to help to maintain.

just add few notes below for further discussion.
from my limited understanding, something we might need to do:

1. create new directory `windows` for windows platform.
2. add library from [nuget](https://www.nuget.org/packages/WebRTC/1.54.1-alpha) or [webrtc-windows](https://github.com/webrtc-uwp/webrtc-windows) ( since webrtc-windows is maintained in another project, so the webrtc version might be different between windows and ios/android )
3. (not sure) porting existing java/ios api to `c#/WinJS`

correct me if I'm wrong.

@Natrium83 do you know is `point 3` necessary? or Microsoft maintained those api and can be used in react-native directly? it's the most time-consuming part.

**Comment by Natrium83** [comment]
In my opinion it should be possible to integrate the native C# code from MS as a plugin for react native. As they ported the original Google WebRTC to UWP it should be nearly the same as the integration of the iOS/Android code. They already provide the JS code, which could an even easier method.

**Comment by saghul** [comment]
@Natrium83 Is not a matter of opinion, but one of technical ability plus time :-)

Can you provide some links where that code is available?

**Comment by Natrium83** [comment]
This is the MS repo

https://github.com/webrtc-uwp/webrtc-uwp-sdk

**Comment by zxcpoiu** [comment]
hmm...just checked it, but didn't see wrapper between `react native js` and `webrtc native libs`.

If anyone knows something more, please share your thoughts.

**Comment by saghul** [comment]
I'm closing this since there is nothing actionable until someone submits a patch.
