### ISSUE TITLE
React/RCTBridgeModule.h file not found Error

### ISSUE THREAD

**Issue by cppiod** [oney/react-native-webrtc#252]
Hi Oney,

Thanks for this react native webrtc project. I'm learning how to use webrtc with React Native. 
I run your demo project successfully on device(iphone), however when I tried to export the xcode project as ipa to do more testing, I encountered this problem: Error, React/RCTBridgeModule.h file not found.
![screenshot 2017-04-10 18 56 57](https://cloud.githubusercontent.com/assets/3303875/24858617/9302b412-1e1f-11e7-8f4c-9b23d939b924.png)
Searched a lot, but not related to this project. I guess may relate to the verison of react or react-native, but not sure. Since the build and run on device work fine, I really wonder why this error come out?

**Comment by Kenny-House** [comment]
Hi @cppiod, I've run into this quite a bit. 

I would double check that the Header Search Path includes `$(BUILT_PRODUCTS_DIR)/usr/local/include`, it's possible that it hasn't been updated since react-native changed the way headers are copied. 

For library projects (not full react-native projects), if that doesn't resolve the issue, you may need to explicitly add the `React` Xcode project to the library's Xcode project, set it to build first, and then build your project after that has completed:

1. Install react-native somewhere locally
2. Open the `react-native` directory, open the `React` subdirectory, drag the `React.xcodeproj` into the Xcode project you're working on (you can place it right below your project name in the Project Navigator)
3. Open the Product -> Scheme - > Edit Scheme menu. Select "Build" on the left if not already selected. Click the `+` and add `React` to the targets. Drag `React` to the top of the list of targets and and uncheck `Parallelize Build`. 
4. Run your build, you'll see the packager startup as React is building, but you can safely close this terminal window. React will build first, then your project. You should see the header issues resolve. You can now remove `React` from your project and remove the `React` target from the scheme (it will show as missing once you remove from the project).

After that, I can usually continue developing as normal.

For reference, when react-native builds, it's headers are copied to a subdirectory within `$(BUILT_PRODUCTS_DIR)`. That's why you'll see a path to that directory (often `$(BUILT_PRODUCTS_DIR)/usr/local/include`) in the Header Search Path in the Build Settings in Xcode. I don't know Xcode build processes well enough to know why those headers are sometimes deleted, but it does happen from time to time. There's an issue on react-native's Github repo that references this process, but I've lost track of my link to it.

**Comment by cppiod** [comment]
Thanks a lot, @Kenny-House 
I've tried add React to target and build it first. It did work 👍 .

**Comment by anand-hsc** [comment]
I don't find any RNDemo project using react-native-webrtc. Actually i want to standalone build react-native-webrtc and getting similar compiler error React/* file not found. How can i fix this
