### ISSUE TITLE
compile webrtc 1.58.0?

### ISSUE THREAD

**Issue by richmonkey** [oney/react-native-webrtc#275]
1. clone webrtc source
2. git checkout -b build-m58 refs/remotes/branch-heads/58

git cherry-pick  338602596
git cherry-pick  e95b78bd8
Is cherry-pick right?

These cherry-picks conflicts, how to fix the conflicts?
Why need this cherry-picks?

I readed https://github.com/oney/react-native-webrtc/pull/229, but i can't understand.

**Comment by richmonkey** [comment]
If needs to fix conflicts,  I think patch is better

**Comment by zxcpoiu** [comment]
please read https://github.com/oney/react-native-webrtc#webrtc-revision

### Why Conflicts?

because #229 is for M57 which cherry-picks some commits from M58
but M58 already contains these commits

### Why Cherry-Picks needed?

No, you don't have to cherry-pick or you can cherry-pick for any commits you want.

If you want to build your own lib, there is no rules that which branch/commits should be.
you can even build the latest master if you want.

the reason this lib do cherry-picks because there are some fixies/features that we think is important but not included in the target branch.

**Comment by zxcpoiu** [comment]
FWIW,

this repo `react-native-webrtc` is a library for react-native which includes `native webrtc lib compiled from branch M58`

there is no `webrtc version 1.58.0` on the earth though.

**Comment by richmonkey** [comment]
@zxcpoiu  Thanks . 
I know 1.58.0 is react-native-webrtc version.
I want to compile webrtc same as react-native-webrtc 1.58.0, because the the latest webrtc can't work with jitsi-videobridge.


I got the 338602596, e95b78bd8 from 
commit id:306c697b167a6d1f06cc9cb5cd29a90ba148f190
Built from commits:
1. 6c9caaad7 (branch-heads/58)
2. 338602596
3. e95b78bd8

**Comment by zxcpoiu** [comment]
oh, okey

if you just want the the same libs with `react-native-webrtc 1.58.0`
you can just grab from this repo

[android libs jar/so](https://github.com/oney/react-native-webrtc/tree/master/android/libs)
[ios Framework](https://github.com/oney/react-native-webrtc/tree/master/ios/WebRTC.framework)

**Comment by zxcpoiu** [comment]
BTW, I thought `cherry-pick` is the right way, the problem is you should know how to resolve those conflicts.
it is not a webrtc issue but a git issue though.

anyway, please check https://githowto.com/resolving_conflicts

1. do `git cherry-pick`
2. edit files and resolve conflicts
3. `git add` those resolved files
4. `git cherry-pick --continue`

**Comment by richmonkey** [comment]
thank you
