### ISSUE TITLE
couldn't find key spdMid error

### ISSUE THREAD

**Issue by simpleblack** [oney/react-native-webrtc#343]
I had error 
This is ios not error only android error

![8aedb727-f9a9-487f-861e-ff039ceb7d48](https://user-images.githubusercontent.com/5565272/30249777-0dad496c-967e-11e7-84ab-d214fe024452.jpg)

**Comment by zxcpoiu** [comment]
This seems a remote party does not containing `sdpMid` in ice candidate but `sdpMid` is our mandatory attribute in `addICECandidate()`.

can you check where the sdp is generated from?

**Comment by simpleblack** [comment]
@zxcpoiu 
My test code this repo.
https://github.com/8enmann/WebtendoClient/blob/master/index.ios.js#L197

IOS run no problem but only Android error

react-native-webrtc use Ios and Android differently?

**Comment by zxcpoiu** [comment]
[android creates java native `IceCandidate` manually via getString/getInt](https://github.com/oney/react-native-webrtc/blob/master/android/src/main/java/com/oney/WebRTCModule/WebRTCModule.java#L795)

[ios initialize objc native `RTCIceCandidate` automatically when invoking the function](https://github.com/oney/react-native-webrtc/blob/master/ios/RCTWebRTC/WebRTCModule%2BRTCPeerConnection.m#L203)

Since webrtc c library use these param as mandatory, I think iOS should fail as well. Why iOS works MAY be because objc initialized `sdpMid` / `sdpMLineIndex` to a default value if it is undefined, and it luckily matched remote stream when you are not in a complex negotiate use case.

you can try to add some fake  `sdpMid` / `sdpMLineIndex = 0` manually as a workaround if your remote party did not support sdpMid.

**Comment by simpleblack** [comment]
@zxcpoiu 
Your detailed reply.
Thanks you.

**Comment by nervouscat** [comment]
Hello @simpleblack ,

I am having the same issue, I would just like to know where you placed the code snippet exactly.

Thank you in advance!

**Comment by simpleblack** [comment]
@nervouscat

In my case

``` javascript
if (rtcSessionDescription.type === 'offer') {
  this._peerConn.setRemoteDescription(new RTCSessionDescription(rtcSessionDescription), function () {}, logError)
  this._peerConn.createAnswer(this._onLocalSessionCreated(sender), logError, sdp_constraints)
} else if (rtcSessionDescription.type === 'answer') {
  this._peerConn.setRemoteDescription(new RTCSessionDescription(rtcSessionDescription), function () {}, logError)
} else if (rtcSessionDescription.type === 'candidate') {
  this._peerConn.addIceCandidate(new RTCIceCandidate({
    sdpMLineIndex: 0,
    sdpMid: 'data',
    candidate: rtcSessionDescription.candidate,
  }))
}
```

**Comment by fukemy** [comment]
hi, can u explain more code about when u add candidate
