### ISSUE TITLE
What is the copyright on this?

### ISSUE THREAD

**Issue by tjbo** [oney/react-native-webrtc#36]
In the root directory it says open source?
 
But in the iOS files it has a copyright notice and "All rights reserved".

I'm just asking, because I am thinking about making a contribution to this project, but would prefer to do it knowing that I can actually use the code.

**Comment by zxcpoiu** [comment]
The author reserved all rights (works/codes) of course.

Since the license of this project is `MIT License`, it means the author grants permissions to other people by using the descriptions from `MIT License` which indicate what you can or can not do with this project.

check this SO question:
[mit-license-and-all-rights-reserved](http://opensource.stackexchange.com/questions/2121/mit-license-and-all-rights-reserved)

**Comment by tjbo** [comment]
Ok thx, that clears it up a bit.

**Comment by zxcpoiu** [comment]
@tjbo yea!! let's do it!
I also have plans to contribute!
to avoid duplicate work, maybe we can open  an issue which addressed a Todo list?
