### ISSUE TITLE
Add support for `react-native-web`

### ISSUE THREAD

**Issue by piranna** [oney/react-native-webrtc#372]
Allow to use `react-native-webrtc` with [react-native-web](https://github.com/necolas/react-native-web) by adding support for native web APIs. A simple solution would be to add [react-native-web-webrtc](https://github.com/liivevideo/react-native-web-webrtc) as a dependency and when detect the web platform delegate the APIs instantiation to it.

**Comment by zxcpoiu** [comment]
I think it's a bit out of scope of this library.
Since this library should also be agnostic.
What you've proposed should be done in the main app for specific use cases.

**Comment by piranna** [comment]
> Since this library should also be agnostic

At this moment, this library is offering support for both Android and iOS, I'm only asking to add support for an extra platform (web) without needing devs to hack around to use one or another...


> What you've proposed should be done in the main app for specific use cases.

How could I be able to map `react-native-webrtc` package to `react-native-web-webrtc` on my app config?

**Comment by zxcpoiu** [comment]
I'm sorry, but I'm not sure what `supporting webrtc api for web platform` means.

do you mean you want to run exactly the same react-native code on the web via `react-native-web` ? and you need `react-native-web-webrtc` to act as web native api ( as a replacement to native module `webrtc.so` )?

**Comment by zxcpoiu** [comment]
does the following works?

```

if platform is 'ios' or 'android'
    WebRTC = require('react-native-webrtc');
else
    WebRTC = require('react-native-web-webrtc'); 


```

**Comment by piranna** [comment]
> do you mean you want to run exactly the same react-native code on the web via react-native-web ?

Yes, that's it.


> does the following works?
> 
> 
> if platform is 'ios' or 'android'
>     WebRTC = require('react-native-webrtc');
> else
>     WebRTC = require('react-native-web-webrtc');

It could work, but seems webpack can be able to define aliases, but I didn't tested it yet. Anyway, on `react-native-webrtc` it would be just enough to add a `index.web.js` file that just exports the object imported from `react-native-web-webrtc` module.

**Comment by zxcpoiu** [comment]
got it.

My only concern is: to add `react-native-web-webrtc` as dependency.
To support what you proposed `web platform` is different to support `android / ios / windows`

because:

* we build the native library ourselves, current version is M58, but modern chrome should be M6x now
  and the behaviors between M5x and M6x are definitely different. it may increase issues that we can not resolve/answer

* The main audiences of this library mainly runs on ios/android, if we add `react-native-web-webrtc` as dependency, npm would complains unnecessary warning and confusing users. 



I think it would be fine if we only have to add `index.web.js` without bother dependence.

Then you can install `react-native-web-webrtc` manually on local because you know what you need and what you are doing. Even if you forgot to install, npm will tell you without confusing.

sounds good?
feel free to fire a PR then.

**Comment by saghul** [comment]
Sounds like a good idea, as long as it doesn't increase the maintenance costs. Feel free to open a PR, I'm going to close this in the meantime.
