### ISSUE TITLE
How to switch to Video Call from Audio Call

### ISSUE THREAD

**Issue by zek** [oney/react-native-webrtc#532]
I am starting call as audio call then I want to open camera when button clicked.

Is there any function to share camera after call

**Comment by zek** [comment]
I know I can just start call as video call and then "enabled=false" but this is not why I want.

**Comment by saghul** [comment]
Closing since this is out of the scope of this plugin. What you ask is a general WebRTC question, please use a forum such as StackOverflow for that. Generally, if you want to add video later you'll want to `getUserMedia` (this time with video) and add the stream to your connection. You'll need to renegotiate.
