### ISSUE TITLE
Crash if camera permission is denied.

### ISSUE THREAD

**Issue by m59peacemaker** [oney/react-native-webrtc#85]
Steps to reproduce:
1. Deny camera permission to the app or toggle it off in the app settings
2. Call getUserMedia.

The error handler is not called. The log doesn't show anything. The app just crashes with EXC_BAD_ACCESS.

**Comment by zxcpoiu** [comment]
I don't know the exact behavior on iOS, but on android, since RN does not officially support android api 23 which introduced request permission at runtime, thus, if you manually revoke permission on device, the app will crash immediately.

Because your app into a unpredictable state and there is no way to ask/check permission at runtime if `targetSdkVersion` is less than 23.

I guess it is the same on iOS, sometimes crash is better than unpredictable.

Anyway, IMO, it is user's responsibility to handle permission state since webrtc is a pure native C++ library and is unlikely to handle permissions for you properly.

you can check permission before you call `getUserMedia`, if it is in denied state, show an alert to user something like that.

**android ( check and request android M runtime permission )**
[react-native-android-permissions](https://github.com/lucasferreira/react-native-android-permissions)

**ios (check only)**
[react-native-permissions](https://github.com/yonahforst/react-native-permissions)

**Comment by m59peacemaker** [comment]
That makes sense. A wrapper could be made for this library's `getUserMedia` that checks the permissions and calls the error callback so that it matches the browser behavior. I'll just do that in my project.

**Comment by zxcpoiu** [comment]
yeah, to make a library to not crash in any situation is also makes sense.

we can port codes like I did in [react-native-incall-manager ios L844](https://github.com/zxcpoiu/react-native-incall-manager/blob/master/ios/RNInCallManager/RNInCallManager.swift#L844)

but it would add some complexity to install and maintain issues. especially on android which needs additional support library to make the check work.

We can keep this issue open for further discussion.

**Comment by lyubomir** [comment]
I fixed this crash in the fork of the Jitsi community yesterday: https://github.com/jitsi/react-native-webrtc/commit/a9b1fad65e2a52f120ff8fa7edf7fd0ccbb2fcfc.
